version: '3.7'
services:
  main:
    image: johnfryer218/main:latest
    build: ./main
    ports:
      - target: 5000
        published: 5000
    deploy:
      replicas: 1
  fizzBuzz:
    image: johnfryer218/fizzbuzz:latest
    build: ./fizzBuzz
    ports:
      - target: 5001
        published: 5001
    deploy:
      replicas: 1
  factorial:
    image: johnfryer218/factorial:latest
    build: ./factorial
    ports:
      - target: 5002
        published: 5002
